# Generated by Django 3.2.13 on 2022-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_description', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'trash',
            },
        ),
    ]
